[build]
  command = "envsubst < src/environments/env.template.ts > src/environments/environment.prod.ts && ng build --configuration production"
  publish = "dist/seu-app"  # ← Substitua 'seu-app' pelo nome real do seu app Angular

[environment]
  NG_API_URL = "https://api.seudominio.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
